### ISSUE TITLE
Link to clock .ino missing / dead

### ISSUE THREAD

**Issue by MacSass** [Utyff/xy-clock#1]
Hi,
this project is highly interesting for me as I do own the same board and the Sinilink app is a nightmare- thanks for providing this information, 

I wanted to point out that the link to [https://github.com/Utyff/xy-clock/blob/master/5-clock/readme.md](https://github.com/Utyff/xy-clock/blob/master/5-clock/readme.md) only returns a 404 error ... can you fix that? Is the code available already?

**Comment by MacSass** [comment]
Guess the right link in the root readme.md should be that:
[https://github.com/Utyff/xy-clock/tree/master/5-clock](https://github.com/Utyff/xy-clock/tree/master/5-clock)
So - I think only the readme.md should be updated ... only a small glitch ...

**Comment by Utyff** [comment]
File 5-clock/readme.md was in uppercase. Fixed.
Be careful, this code not yet tested on a 8285 chip. Only on 8266.
