### ISSUE TITLE
Changing / lowering minimum brightness?

### ISSUE THREAD

**Issue by MacSass** [Utyff/xy-clock#2]
Hi,
thanks for your HW analysis - this is really helpful.
I have one request, I hope you could help with: For me the lowest brightness level is still way to high and disturbing at night.

I would like to modify the HW to have a much lower brightness level. Would you have any idea how to do this:
- Could I add / change a resistor somewhere in order to lower voltage to LEDs?
- How does the chip control the overall brightness? Could that be used to lower it further somehow?

Thanks in advance for any ideas you might have ...

**Comment by Utyff** [comment]
For brightness conrol used PWM. Read here for detail https://github.com/maarten-pennings/303WIFILC01/tree/main/4-display.
If lowest level is not enought try to
 add resistors ~100 ohm into LED circuts DIG*.
 ![1](https://user-images.githubusercontent.com/13304142/209487554-f6ecd6a4-6979-4183-b03e-dfbda80650d9.JPG)

**Comment by MacSass** [comment]
Thanks for your feedback - adding resistors to those might not be easy as I would have to cut 4 traces and and 4 resistors, if I understand correctly ... wondering if I go back to my initial plan of adding a grey filter in front of the LEDs to reduce brightness.
Not sure ... but thanks for your inputs, highly appreciated!
